### ISSUE TITLE
Rune colors

### ISSUE THREAD

**Issue by zachcd** [kresozd/gemtowerdefense#1]
Diamond - 

Ruby - Haste

Amethyst

Aquamarine

Emerald - Regeneration

Sapphire - Double Damage

Topaz - Illusion

Opals -

left are arcane, invis, bounty for Diamond, Amethyst, Aquamarine, Opal.

Opals could be a multicolored rune or something distinct from the other gems.

**Comment by kresozd** [comment]
My friend is working on custom rune models. I told him to basically remodel the runes and add a bit of more detail to them.

**Comment by zachcd** [comment]
Sounds great
